baseURL = "https://example.org/"
languageCode = "en-us"
title = "REXPEK - Reproducing Expert Knowledge"
theme = "hugo-arcana"
copyright = "© Untitled. All rights reserved"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1

[taxonomies]
    tag = "tags"

[params]
    description = "REXPEK - Suggest optimal machine settings through virtual & on-site experimentation"
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/FlandersMake"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/flanders-make/"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/REXPEK"


    [params.footer]
        [[params.footer.links]]
            header = "About us"
        [[params.footer.links.links]]
            title = "Project Profile"
            url = "/project-profile"
        [[params.footer.links.links]]
            title = "Flanders Make"
            url = "https://www.flandersmake.be/en"
        [[params.footer.links.links]]
            title = "Electrical Energy Lab (UGent)"
            url = "https://www.ugent.be/ea/emsme/en/research/eelab/electrical-energy-laboratory"
        [[params.footer.links.links]]
            title = "DecisionS Lab (Flanders Make)"
            url = "#"
        [[params.footer.links.links]]
            title = "DTAI Research (KU Leuven)"
            url = "https://wms.cs.kuleuven.be/dtai/research/ResearchTopics#FUND"

        [[params.footer.links]]
            header = "Contact us"
        [[params.footer.links.links]]
            title = "Address: "
            url = "#footer" # google map
        [[params.footer.links.links]]
            title = "Hotline: "
        [[params.footer.links.links]]
            title = "Email: "
            url = "#footer"


        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
