baseURL = "https://example.org/"
languageCode = "en-us"
title = "REXPEK - Reproducing Expert Knowledge"
theme = "hugo-arcana"
copyright = "© Untitled. All rights reserved"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1

[taxonomies]
    tag = "tags"

[params]
    description = "REXPEK - Suggest optimal machine settings through virtual & on-site experimentation"
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/FlandersMake"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/flanders-make/"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/REXPEK"

    [params.footer]
        [[params.footer.links]]
            header = "About us"
        [[params.footer.links.links]]
            title = "Project Profile"
            url = "/project-profile"
        [[params.footer.links.links]]
            title = "Flanders Make"
            url = "https://www.flandersmake.be/en"
        [[params.footer.links.links]]
            title = "M&F Groups (Ugent)"
            url = "https://www.ugent.be/m-f/en"
        [[params.footer.links.links]]
            title = "Dynamics Design Lab (Ugent)"
            url = "https://dynamics.ugent.be/"
        [[params.footer.links.links]]
            title = "Flanders Make @ KU Leuven"
            url = "https://www.kuleuven.be/flandersmake"
        [[params.footer.links.links]]
            title = "DTAI Research (KU Leuven)"
            url = "https://dtai.cs.kuleuven.be/"

        [[params.footer.links]]
            header = "Contact us"
        [[params.footer.links.links]]
            title = "Address: Gaston Geenslaan 8 3001 Heverlee Belgium"
            url = "https://maps.app.goo.gl/LzWGVDpcwCDwuxCF8" # google map
        [[params.footer.links.links]]
            title = "Hotline: +32 11 790 590 "

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
